{
  "item": "Crispy Chicken Sandwich",
  "allergens": ["Milk", "Wheat", "Soy"],
  "dietary_restrictions": "None",
  "religious_restrictions": "None",
  "serving_size": "Sandwich",
  "nutrition_facts": {
    "calories": 350,
    "total_fat_g": 14,
    "saturated_fat_g": 1,
    "cholesterol_mg": 30,
    "sodium_mg": 610,
    "total_carbohydrate_g": 41,
    "dietary_fiber_g": 5,
    "total_sugars_g": 3,
    "added_sugars_g": 3,
    "protein_g": 18,
    "vitamin_d_mcg": 7,
    "calcium_mg": 110,
    "iron_mg": 2,
    "potassium_mg": 130
  }
},

{
  "item": "Bagel with Cream Cheese",
  "components": {
    "bagel": {
      "allergens": ["Wheat"],
      "dietary_restrictions": "None",
      "religious_restrictions": "None",
      "serving_size": "Bagel",
      "nutrition_facts": {
        "calories": 170,
        "total_fat_g": 1,
        "sodium_mg": 300,
        "total_carbohydrate_g": 35,
        "dietary_fiber_g": 1,
        "total_sugars_g": 3,
        "protein_g": 6,
        "calcium_mg": 30,
        "iron_mg": 2,
        "potassium_mg": 10
      }
    },
    "cream_cheese": {
      "allergens": ["Milk"],
      "dietary_restrictions": "None",
      "religious_restrictions": "None",
      "serving_size": "Each",
      "nutrition_facts": {
        "calories": 70,
        "total_fat_g": 6,
        "saturated_fat_g": 4,
        "cholesterol_mg": 20,
        "sodium_mg": 100,
        "total_carbohydrate_g": 2,
        "total_sugars_g": 2,
        "added_sugars_g": 1,
        "protein_g": 1,
        "calcium_mg": 32
      },
      "ingredients": [
        "Pasteurized Milk and Cream",
        "Cheese Culture",
        "Salt",
        "Guar Gum",
        "Citric Acid",
        "Carob Bean Gum",
        "Xanthan Gum",
        "Natamycin (A Natural Mold Inhibitor)"
      ]
    }
  }
},

{
  "item": "Cereal Meal",
  "components": {
    "cinnamon_chex": {
      "allergens": [],
      "dietary_restrictions": "None",
      "religious_restrictions": "None",
      "serving_size": "Each",
      "nutrition_facts": {
        "calories": 230,
        "total_fat_g": 5,
        "saturated_fat_g": 1,
        "sodium_mg": 320,
        "total_carbohydrate_g": 46,
        "dietary_fiber_g": 3,
        "total_sugars_g": 12,
        "added_sugars_g": 12,
        "protein_g": 3,
        "vitamin_a_iu": 500,
        "vitamin_c_mg": 6,
        "vitamin_d_mcg": 2,
        "calcium_mg": 100,
        "iron_mg": 14
      },
      "ingredients": [
        "Whole Grain Rice",
        "Rice",
        "Sugar",
        "Canola and/or Sunflower Oil",
        "Salt",
        "Cinnamon",
        "Molasses",
        "Natural Flavor",
        "Vitamin E (mixed tocopherols) Added to Preserve Freshness",
        "Calcium Carbonate",
        "Iron",
        "Zinc (mineral nutrients)",
        "Vitamin C (sodium ascorbate)",
        "Niacinamide",
        "Vitamin B2 (riboflavin)",
        "Vitamin B6 (pyridoxine hydrochloride)",
        "Vitamin B1 (thiamin mononitrate)",
        "Vitamin A (palmitate)",
        "Folic Acid",
        "Vitamin B12",
        "Vitamin D3"
      ]
    },
    "blueberry_chex": {
      "allergens": [],
      "dietary_restrictions": "None",
      "religious_restrictions": "None",
      "serving_size": "Each",
      "nutrition_facts": {
        "calories": 240,
        "total_fat_g": 5,
        "saturated_fat_g": 1,
        "sodium_mg": 350,
        "total_carbohydrate_g": 46,
        "dietary_fiber_g": 1,
        "total_sugars_g": 12,
        "added_sugars_g": 12,
        "protein_g": 3,
        "vitamin_a_iu": 500,
        "vitamin_c_mg": 6,
        "vitamin_d_mcg": 2,
        "calcium_mg": 100,
        "iron_mg": 16
      },
      "ingredients": [
        "Whole Grain Rice",
        "Rice",
        "Sugar",
        "Canola Oil",
        "Blueberry Powder",
        "Salt",
        "Molasses",
        "Natural Flavor",
        "Vitamin E (mixed tocopherols) Added to Preserve Freshness",
        "Calcium Carbonate",
        "Iron",
        "Zinc (mineral nutrients)",
        "Vitamin C (sodium ascorbate)",
        "Niacinamide",
        "Vitamin B2 (riboflavin)",
        "Vitamin B6 (pyridoxine hydrochloride)",
        "Vitamin B1 (thiamin mononitrate)",
        "Vitamin A (palmitate)",
        "Folic Acid",
        "Vitamin B12",
        "Vitamin D3"
      ]
    },
    "honey_cheerios": {
      "allergens": [],
      "dietary_restrictions": "None",
      "religious_restrictions": "None",
      "serving_size": "Each",
      "nutrition_facts": {
        "calories": 210,
        "total_fat_g": 3,
        "saturated_fat_g": 1,
        "sodium_mg": 340,
        "total_carbohydrate_g": 44,
        "dietary_fiber_g": 5,
        "total_sugars_g": 12,
        "added_sugars_g": 12,
        "protein_g": 6,
        "vitamin_a_iu": 750,
        "vitamin_c_mg": 9,
        "vitamin_d_mcg": 3,
        "calcium_mg": 150,
        "iron_mg": 5,
        "potassium_mg": 282
      },
      "ingredients": [
        "Whole Grain Oats",
        "Sugar",
        "Corn Starch",
        "Honey",
        "Brown Sugar Syrup",
        "Salt",
        "Tripotassium Phosphate",
        "Canola and/or Sunflower Oil",
        "Natural Flavor",
        "Vitamin E (mixed tocopherols) Added to Preserve Freshness",
        "Calcium Carbonate",
        "Vitamin C (sodium ascorbate)",
        "Iron",
        "Zinc (mineral nutrients)",
        "Niacinamide",
        "Vitamin B6 (pyridoxine hydrochloride)",
        "Vitamin B1 (thiamin mononitrate)",
        "Vitamin A (palmitate)",
        "Vitamin B2 (riboflavin)",
        "Folic Acid",
        "Vitamin B12",
        "Vitamin D3"
      ]
    },
    "cinnamon_toast_crunch_less_sugar": {
      "allergens": ["Wheat", "Soy"],
      "dietary_restrictions": "None",
      "religious_restrictions": "None",
      "serving_size": "Each",
      "nutrition_facts": {
        "calories": 210,
        "total_fat_g": 5,
        "saturated_fat_g": 1,
        "sodium_mg": 320,
        "total_carbohydrate_g": 44,
        "dietary_fiber_g": 7,
        "total_sugars_g": 11,
        "added_sugars_g": 11,
        "protein_g": 3,
        "vitamin_a_iu": 500,
        "vitamin_c_mg": 6,
        "vitamin_d_mcg": 2,
        "calcium_mg": 100,
        "iron_mg": 5,
        "potassium_mg": 94
      },
      "ingredients": [
        "Whole Grain Wheat",
        "Sugar",
        "Rice Flour",
        "Polydextrose",
        "Canola and/or Sunflower Oil",
        "Maltodextrin",
        "Dextrose",
        "Salt",
        "Cinnamon",
        "Trisodium Phosphate",
        "Soy Lecithin",
        "Caramel Color",
        "Rosemary Extract",
        "BHT Added to Preserve Freshness",
        "Calcium Carbonate",
        "Vitamin C (sodium ascorbate)",
        "Iron",
        "Zinc (mineral nutrients)",
        "Niacinamide",
        "Vitamin B6 (pyridoxine hydrochloride)",
        "Vitamin B1 (thiamin mononitrate)",
        "Vitamin A (palmitate)",
        "Vitamin B2 (riboflavin)",
        "Folic Acid",
        "Vitamin B12",
        "Vitamin D3"
      ]
    }
  }
},

